### ISSUE TITLE
gtkdialog throws warnings under X under cage

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/gtkdialog#106]
See https://github.com/puppylinux-woof-CE/woof-CE/issues/2670

An attempt was made to fix in #105 

I'm going to try `getenv(WAYLAND_DISPLAY)` _but_ it still might throw the warnings under `cage` running X as a child.

We'll see.

**Comment by 01micko** [comment]
Ok, here's the diff **not yet tested on `cage`**

```diff
diff -rupN gtkdialog/src/widget_window.c gtkdialog-getenv/src/widget_window.c
--- gtkdialog/src/widget_window.c	2021-12-12 05:49:30.252442655 +1000
+++ gtkdialog-getenv/src/widget_window.c	2021-12-12 06:29:13.552477897 +1000
@@ -25,6 +25,7 @@
 #include "config.h"
 #if HAVE_GTK_LAYER_SHELL
 #include <gtk-layer-shell.h>
+#include <stdlib.h>
 #endif
 #include "gtkdialog.h"
 #include "attributes.h"
@@ -98,6 +99,9 @@ GtkWidget *widget_window_create(
 	widget = gtk_window_new(GTK_WINDOW_TOPLEVEL);  
 
 #if HAVE_GTK_LAYER_SHELL
+	if (!getenvnv("WAYLAND_DISPLAY"))
+		goto layer_set;
+
 	GtkLayerShellLayer layer = GTK_LAYER_SHELL_LAYER_ENTRY_NUMBER;
 
 	value = get_tag_attribute(attr, "layer");
@@ -167,6 +171,7 @@ GtkWidget *widget_window_create(
 		}
 	}
 
+layer_set:
 #endif
 
 	/* Set a default window title */
```

**Comment by 01micko** [comment]
Ok, the `XAUTHORITY` environmental variable is key - zipped binary attached at bottom

## X under Cage

![cage-gtkdialog](https://user-images.githubusercontent.com/1019119/145692488-dc185a03-0dfa-4e74-9ec2-77251dfb41fe.png)

---

## pure X

![x-gtkdialog](https://user-images.githubusercontent.com/1019119/145692507-f842d43a-6fe6-47d8-a57d-6d3b0297a4e2.png)

---

## labwc

![gtkdialog](https://user-images.githubusercontent.com/1019119/145692599-b96322b2-7065-4020-8f43-bc96d88c17cd.png)

---

[gtkdialog.zip](https://github.com/puppylinux-woof-CE/gtkdialog/files/7697788/gtkdialog.zip)

**Comment by dimkr** [comment]
I *think* this should work:

```
      GdkWindow *window = gtk_widget_get_window (widget);
      GdkDisplay *display = gdk_window_get_display(window);
      if (GDK_IS_WAYLAND_DISPLAY (display)) {
           ....
      }
```

**Comment by 01micko** [comment]
Ok, I'll try something like that.

**Comment by 01micko** [comment]
Tried a few different ways all ending up with this critical warning:

```
(gtkdialog:28587): Gdk-CRITICAL **: 17:20:04.412: gdk_window_get_display: assertion 'GDK_IS_WINDOW (window)' failed
```

**Comment by 01micko** [comment]
IMHO, I can't see anything wrong with `getenv("GDK_BACKEND")`and doing a `strncmp()`, so looks like I have to do the hard sell (_sidenote_: sold my old [ute](https://en.wikipedia.org/wiki/Ute_(vehicle)) today :rofl: and got more than I paid for it 2 years ago) 

1. `GDK_BACKEND` _must_ to be set to `wayland` whether using pure wayland or wayland with Xwayland or most gtk stuff just won't run, including firefox
2. X11 under cage has `GDK_BACKEND` set to `x11`
3. old normal puppy distros (pre our adventures with wayland) `GDK_BACKEND` is not set 

So there is a case there where where we *should* be failsafe.

I'm happy to hear alternatives but I want this fixed ASAP, and get a `labwc` alpha out before Santa gets his presents out.

**Comment by 01micko** [comment]
0.8.4h released.
