### ISSUE TITLE
gtk3 vte2 fg/bg/cursor color VTE-CRITICAL error

### ISSUE THREAD

**Issue by step-** [puppylinux-woof-CE/gtkdialog#136]
With **gtk3 3.22.30 and libvte2_91 0.59.0 on Fatdog64-812 run `./examples/terminal/terminal`. While the script is starting multiple critical errors concern setting the background, foreground, cursor and highlight colors.

```
(gtkdialog:13507): VTE-CRITICAL **: 09:29:46.719: void vte_terminal_set_color_background(VteTerminal*, const GdkRGBA*): assertion 'valid_color(background)' failed

(gtkdialog:13507): VTE-CRITICAL **: 09:29:46.719: void vte_terminal_set_color_foreground(VteTerminal*, const GdkRGBA*): assertion 'valid_color(foreground)' failed

(gtkdialog:13507): VTE-CRITICAL **: 09:29:46.719: void vte_terminal_set_color_cursor(VteTerminal*, const GdkRGBA*): assertion 'cursor_background == nullptr || valid_color(cursor_background)' failed

(gtkdialog:13507): VTE-CRITICAL **: 09:29:46.719: void vte_terminal_set_color_highlight(VteTerminal*, const GdkRGBA*): assertion 'highlight_background == nullptr || valid_color(highlight_background)' failed
```

The dialog is displayed but tab 2, "Colourful", displays default colors instead of custom colors.  The expected correct behavior should be no `VTE-CRITICAL` errors and custom colors displayed in tab 2.

**Comment by 01micko** [comment]
Do you have any idea how to fix?

If possible it should be fixed before `0.8.5` release.

**Comment by step-** [comment]
I do have an idea.  Will try to make 0.8.5.

**Comment by 01micko** [comment]
No rush :)
