### ISSUE TITLE
Last call for last minute inclusions for v0.8.5

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/gtkdialog#143]
@dimkr , @step- , @woodenshoe-wi and anyone else.

Do you have any last minute inclusions?

I think `gtkdialog` is in a good place ATM. It's working pretty well everywhere where it supposed to. 

I'm working on the wiki to bring it into line with the `html` pages.

So .. **last call** ! :mega:

**Comment by 01micko** [comment]
`wiki` is almost done.

**Comment by dimkr** [comment]
Mabye https://github.com/puppylinux-woof-CE/woof-CE/issues/2964 is worth taking at least a quick look?

**Comment by 01micko** [comment]
Sure. :-)

**Comment by step-** [comment]
I'm happy with the current state!

**Comment by dimkr** [comment]
https://github.com/puppylinux-woof-CE/woof-CE/issues/2964 can be fixed later: we have the workaround of using a GTK+ 2 build of gtkdialog, and this tool has no use in a pure Wayland setup without GTK+ 2.

**Comment by 01micko** [comment]
I did a _huge_ cleanup on the docs. PR soon. Wiki will be updated shortly. If anyone wants just take a look at wiki versus docs for any conflicting info but I think it's ok.

Once that's done I'll release `0.8.5`

Thanks all!

**Comment by step-** [comment]
Found `0.4.8+` in the Notes section of https://github.com/puppylinux-woof-CE/gtkdialog/wiki/chooser. Replace with `0.8.5`.

502 error page following Gtk3 links similar to https://github.com/puppylinux-woof-CE/gtkdialog/pull/144#issuecomment-1079696457

**Comment by 01micko** [comment]
> Found `0.4.8+` in the Notes section of https://github.com/puppylinux-woof-CE/gtkdialog/wiki/chooser. Replace with `0.8.5`.
> 
> 502 error page following Gtk3 links similar to [#144 (comment)](https://github.com/puppylinux-woof-CE/gtkdialog/pull/144#issuecomment-1079696457)

Fixed. Thanks

**Comment by 01micko** [comment]
It's out!
