### ISSUE TITLE
Compile in OSX (with homebrew installed)

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/gtkdialog#81]
With the little patch below (also git formatted and attached gzipped) compiles fine in both linux and OSX. Not a target OS so not sure if a pull worth it. 
```
--- a/src/automaton.c	2017-11-16 07:27:06.000000000 +0200
+++ b/src/automaton.c	2017-11-16 07:21:33.000000000 +0200
@@ -1295,7 +1295,7 @@
    Miert nem kapja meg az adatokat parameterben es foglalkozik
    a veremmel a hivo?
  */
-#ifdef __arm__
+#if defined(__arm__) || defined(__APPLE__)
 /* 120701 BK Puppy Linux forum member jamesbond fixed this for arm cpus...*/
 stackelement _sum(stackelement b, stackelement a)
 #else
--- a/src/variables.c	2017-11-16 07:27:06.000000000 +0200
+++ b/src/variables.c	2017-11-16 07:22:42.000000000 +0200
@@ -1113,7 +1113,7 @@
 		actual = root;
 
 	if (actual == NULL)
-		return;
+		return 0;
 
 	if (actual->left != NULL)
 		n = do_variables_count_widgets(actual->left, n);
```
[0001-Mods-for-OS-X-with-homebrew.patch.gz](https://github.com/01micko/gtkdialog/files/1477438/0001-Mods-for-OS-X-with-homebrew.patch.gz)

**Comment by 01micko** [comment]
I'll probably merge the patch but knowing Apple a 'curve ball' could be thrown any time :stuck_out_tongue:

**Comment by mavrothal** [comment]
I do not know... how many crazy people you think want to run puppy/gtkdialog/gtk2 apps on a Mac under OS X? 4...? 5...? :roll_eyes: 😛 
Does not harm Linux though, so maybe.

**Comment by dericed** [comment]
Using this patch, I was able to run gtkdialog on a Mac, so please +1 to the list of crazy people.
