### ISSUE TITLE
Here is a fix for aarch64

### ISSUE THREAD

**Issue by bkauler** [puppylinux-woof-CE/gtkdialog#84]
Hi guys, I have a patch for you. gtkdialog renders widgets incorrectly on aarch64, this link explains and has a patch:

http://bkhome.org/news/201807/fix-widget-order-for-gtkdialog-aarch64.html

**Comment by 01micko** [comment]
Barry, so sorry for late reply, but I'm not _really_ the maintainer of gtkdialog!

We should put it under puppy-linux-woof-ce repo, which I will look into.

I'm wondering if we can shorten the code a bit with simple `||` as in @mavrothal 's patch #81  for mac computers, which are x86_64. (Digression: this is probably a bug in the compiler and _not_ gtkdialog. Anyone compiled this with _clang_ ?)

Anyway, if you feels so inclined would you like to test something like:

```C
#if defined(__arm__) || defined(__APPLE__) || defined(__aarch64__)
```
:question:
