### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by sc0ttj** [puppylinux-woof-CE/gtkdialog#86]
https://github.com/topics/gtkdialog

^ gtkdialog doesn't even show up here, let alone all the apps made with it

**Comment by 01micko** [comment]
This repo really should be moved to woof-ce, then we can have a broader audience.

**Comment by woodenshoe-wi** [comment]
On the subject of documentation...

I had converted the google code documentation into GitHub wiki format https://github.com/woodenshoe-wi/gtkdialog/wiki

But I don’t know how to issue a pull request for an entire wiki repo.

See https://github.com/01micko/gtkdialog/pull/83#issuecomment-385745505
