### ISSUE TITLE
gtk3: patch for better line wrapping in text

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/gtkdialog#94]
Ok, did a little research and this does seem like a better idea than the environment variable in Puppy to reduce the ridiculous length of lines inside the text widget which go full screen width if you allow them.

Here's the patch:

```diff
patch removed see below
```

Here's a simple demo script
```shell
#!/bin/sh
EXEC=$1

echo '<window>
	<vbox>
		<text>
			<label>Toggles line wrapping within the GtkLabel widget. TRUE makes it break lines if text exceeds the widget’s size. FALSE lets the text get cut off by the edge of the widget if it exceeds the widget size.Note that setting line wrapping to TRUE does not make the label wrap at its parent container’s width, because GTK+ widgets conceptually can’t make their requisition depend on the parent container’s size. For a label that wraps at a specific position, set thelabel’s width using gtk_widget_set_size_request().</label>
		</text>
		<hbox><button ok></button></hbox>
	</vbox>
</window>' | $EXEC -s
```

As that script is, I used my stock `gtkdialog` as the arg, my patched gtk3 `./gtkdialog`, then a freshly built `./gtkdialog2` - built for gtk-2.0.

And the resultant GUI

![gtkdialog-xxx](https://user-images.githubusercontent.com/1019119/115008334-847f0080-9e9a-11eb-9746-2a06c7869282.jpg)

Thoughts @dimkr , @woodenshoe-wi

**Comment by dimkr** [comment]
https://developer.gnome.org/gtk3/stable/GtkLabel.html#label-text-layout

```
 “width-chars”              int

The desired width of the label, in characters. If this property is set to -1, the width will be calculated automatically.
```

Can `width-chars` be calculated based on the width of the window?

**Comment by 01micko** [comment]
yes.. so `width-chars` doesn't seem to work. Not with gtkdialog anyway

> Can `width-chars` be calculated based on the width of the window?

I don't know how - but I can get the current monitor size in pixels. I decided to calculate the size of `gtk_label_set_max_width_chars(GTK_LABEL(widget), max_width);` (`max-width`).
I have a dual monitor setup so obviously had to get the default screen, my chars computed to 120. I decided to go with half of the screen width in pixels, and one third on larger monitors, roughly converted to chars - very rough because there could be wide chars, bigger font sizes all sorts. Anyway, another patch - but does need some error checking EG: `gdk_display_get_default();` can return `NULL` in which case gtkdialog would probably crash anyway so not going to do at the moment.

~And another thing - I should add a version check because `GdkMonitor` wasn't introduced until gtk+-3.2.2.~

```diff
diff -rup a/src/widget_text.c b/src/widget_text.c
--- a/src/widget_text.c	2020-07-09 08:39:38.173935231 +1000
+++ b/src/widget_text.c	2021-04-17 09:09:01.841340829 +1000
@@ -91,6 +91,22 @@ GtkWidget *widget_text_create(
 	/* Enable line wrapping by default */
 	gtk_label_set_line_wrap(GTK_LABEL(widget), TRUE);
 
+#if GTK_CHECK_VERSION(3,2,2)	/* gtk3: try global max-width-chars fix */
+	GdkDisplay * display = gdk_display_get_default();
+	GdkMonitor * monitor = gdk_display_get_primary_monitor(display);
+	int scale = gdk_monitor_get_scale_factor(monitor);
+	GdkRectangle workarea = {0};
+	gdk_monitor_get_workarea(monitor,&workarea);
+	int width = workarea.width / scale;
+	int max_width;
+	if ( width >= 1920 ) { /* make gui narrrower on wide screens*/
+		max_width = width / 24; 
+	} else {
+		max_width = width / 16; 
+	}
+	gtk_label_set_max_width_chars(GTK_LABEL(widget), max_width);
+#endif
+
 #ifdef DEBUG_TRANSITS
 	fprintf(stderr, "%s(): Exiting.\n", __func__);
 #endif

```

**Comment by 01micko** [comment]
Running my binary in qemu 1024 x 768 resolution

![gtkdialog-qemu](https://user-images.githubusercontent.com/1019119/115094400-e6784e00-9f0c-11eb-8377-2d40df9c4913.png)
