### ISSUE TITLE
make error with implicit declaration of function

### ISSUE THREAD

**Issue by dericed** [puppylinux-woof-CE/gtkdialog#96]
Hi, thanks for your work on this project. I've been using the 0.8.3 version of this code at https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/gtkdialog/gtkdialog-0.8.3.tar.gz and hoping to move to this repo. 
When I run `./autogen.sh && make`, I get this error. I'm on a Mac.

```
gtkdialog.c:639:2: error: implicit declaration of function 'gtkdialog_parse' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        gtkdialog_parse();
        ^
7 warnings and 1 error generated.
make[3]: *** [gtkdialog.o] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

**Comment by 01micko** [comment]
Hi @dericed 

Firstly, I gather that running `autogen.sh` with no args it is trying to compile against gtk+-2.0. I'd be interested if the same error occurs with 
```
autogen.sh  --enable-gtk3 && make
```
so long as you have gtk+3.0 and headers installed.

I suspect it will fail similarly.

I'm not the `C` language expert here but I do have access to a macbook air 2012. It would also be helpful to know the the OS version, the compiler and version.

Thanks for your report.

**Comment by dericed** [comment]
Hi @01micko,
I already have gtk+3 installed via brew
```
% brew info gtk+3
gtk+3: stable 3.24.28 (bottled)
Toolkit for creating graphical user interfaces
https://gtk.org/
/usr/local/Cellar/gtk+3/3.24.28 (716 files, 52MB) *
  Poured from bottle on 2021-04-20 at 11:46:31
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/gtk+3.rb
License: LGPL-2.0-or-later
==> Dependencies
Build: docbook ✔, docbook-xsl ✔, gobject-introspection ✔, meson ✔, ninja ✔, pkg-config ✔
Required: atk ✔, gdk-pixbuf ✔, glib ✔, gsettings-desktop-schemas ✔, hicolor-icon-theme ✔, libepoxy ✔, pango ✔
==> Analytics
install: 31,112 (30 days), 95,844 (90 days), 304,800 (365 days)
install-on-request: 16,268 (30 days), 47,428 (90 days), 133,762 (365 days)
build-error: 0 (30 days)
```

I'm running macOS 11.2.3.

I cleaned my repo and retried with --enable-gtk3. I see that the argument works as expected with
`checking for 		gtk+-3.0 >= 3.0.0... yes`

but ends similarly
```
gtkdialog.c:639:2: error: implicit declaration of function 'gtkdialog_parse' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        gtkdialog_parse();
        ^
6 warnings and 1 error generated.
make[3]: *** [gtkdialog.o] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

full output at https://gist.github.com/dericed/2c6e8ed5297e93b6cd94b5d79c981fbd

Happy to help with other tests.

**Comment by 01micko** [comment]
Maybe a  `C` language dialect problem. I can't get past configure (on Linux) using `CFLAGS=' -std=C99' ./autogen.sh` but am ok if I use `-std=gnu99`.

Maybe try  `CFLAGS=' -std=gnu99' ./autogen.sh` (options to autogen.sh as you like)

Also, it would be interesting to know if the old google-code source for 0.8.3 still compiles for you.

NOTE: out of luck on the mac until I can find out my wife's apple id.

**Comment by dericed** [comment]
Thanks. I had earlier tried `./autogen.sh CFLAGS=" -std=c90"` without success. Trying the command as you suggested gives the same result as well.

I tried again on the 0.8.3 google code and `./autogen.sh && make` fails the same way.

I have a homebrew installer though for gtkdialog 0.8.3 at https://github.com/amiaopensource/homebrew-amiaos/blob/master/gtkdialog.rb and that works, here it the log of that.

A log of that working: https://gist.github.com/dericed/2fac986d82de6cca604ef414861806f1

There it uses `./configure && make` though since the configure file is already there.

**Comment by 01micko** [comment]
Maybe you could try that `gtkdialog.rb` script like so:

- Remove the condition at the top, just point the source to the 0.8.4c release. (or 0.8.4d if you are adventurous updating the checksum) and change back to `autogen.sh`
- Remove the first patch
```diff
diff -urN a/src/automaton.c b/src/automaton.c
--- a/src/automaton.c	2017-11-16 07:27:06.000000000 +0200
+++ b/src/automaton.c	2017-11-16 07:21:33.000000000 +0200
@@ -1295,7 +1295,7 @@
    Miert nem kapja meg az adatokat parameterben es foglalkozik
    a veremmel a hivo?
  */
-#ifdef __arm__
+#if defined(__arm__) || defined(__APPLE__)
 /* 120701 BK Puppy Linux forum member jamesbond fixed this for arm cpus...*/
 stackelement _sum(stackelement b, stackelement a)
 #else
```
That is already in the current source.

BTW, I don't know of anyone who has tried using `clang` to build this, but if it works on 0.8.3 then it should on 0.8.4

**Comment by 01micko** [comment]
I'll try and contact @mavrothal who is our resident mac expert. He might be around as I had contact with him earlier this year.

**Comment by dericed** [comment]
Thank you. With your recommendations I updated the installation formula at https://github.com/amiaopensource/homebrew-amiaos/pull/283/files and it works for me. If you add the 2nd patch here, I'm remove it from the formula for the next release. Thanks again and feel welcome to close this.

**Comment by 01micko** [comment]
Excellent!
